version: '3.8'

services:
  backend:
    platform: "linux/amd64"
    env_file:
      - .env
    volumes:
      - ./backend:/code
    depends_on:
      - db
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    command: uvicorn app.main:app --proxy-headers --host 0.0.0.0 --port 8000 --reload
