version: '3.8'

services:
  backend:
    platform: "linux/amd64"
    env_file:
      - .env
    depends_on:
      - db
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - 8000:8000
  db:
    image: postgres
    env_file:
      - .env
    volumes:
      - ./pg-db:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_DB=$DB_DATABASE
